# Generated by Django 5.0.6 on 2024-06-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('today', '0002_remove_upload_image_date_upload_image_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_image',
            name='merged_image_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
