# Generated by Django 5.0.6 on 2024-06-12 07:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('today', '0003_upload_image_merged_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_image',
            name='image',
        ),
        migrations.RemoveField(
            model_name='upload_image',
            name='merged_image_path',
        ),
        migrations.AddField(
            model_name='upload_image',
            name='merged_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/merged/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload_image',
            name='original_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/original/'),
            preserve_default=False,
        ),
    ]
