# Generated by Django 5.0.6 on 2024-06-12 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('today', '0007_remove_upload_image_merged_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload_image',
            old_name='merged_image_path',
            new_name='merged_image',
        ),
    ]
