# Generated by Django 5.0.6 on 2024-06-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('today', '0008_rename_merged_image_path_upload_image_merged_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_image',
            name='merged_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
