# Generated by Django 5.0.6 on 2024-06-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('today', '0009_alter_upload_image_merged_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_image',
            name='merged_image',
            field=models.ImageField(blank=True, upload_to='merged_images/'),
        ),
    ]
